require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - db/schema.rb
    - config/application.rb
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - 'context'
    - 'describe'
    - 'it'
    - 'configure'

Metrics/MethodLength:
  Max: 20

Lint/MissingSuper:
  Exclude:
    - app/services/**/*
    - app/policies/**/*
