default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: app_development
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>

test:
  <<: *default
  database: app_test
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>

staging:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
